name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CICD_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run Generator 1
        run: docker run --name generator1 -v $(pwd)/k6results:/results ghcr.io/apelsinovich/k6cicd/myk6test:latest run --out json=/results/output.json test.js
      
      - name: Upload Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: k6-test-results
          path: k6results/
      
      - name: Cleanup
        if: always()
        run: |
          docker stop generator1
          docker rm generator1