name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Pull and Run Docker Image
      run: |
        docker pull ghcr.io/apelsinovich/k6cicd/myk6test:latest
        docker run ghcr.io/apelsinovich/k6cicd/myk6test:latest