name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - uses: actions/checkout@v2

      - name: Debug token presence
        run: echo "${{ secrets.CICD_TOKEN }}" | head -c 5  # This will show only the first 5 characters for checking

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CICD_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker Image
        run: docker pull ghcr.io/apelsinovich/k6cicd/myk6test:latest

      - name: Run Generator 1
        run: docker run -d --name generator1 ghcr.io/apelsinovich/k6cicd/myk6test:latest

      - name: Run Generator 2
        run: docker run -d --name generator2 ghcr.io/apelsinovich/k6cicd/myk6test:latest